name: Python CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        # Add other dependencies as needed

    - name: Linting
      run: flake8 pycode.py

    - name: Testing
      run: python pycode.py

  deploy_local:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Vagrant
        run: vagrant --version || sudo apt-get install vagrant

      - name: Deploy to Local Environment
        run: |
          bash deploy_local.sh
