name: Build and Deploy Locally

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      run: docker --version

    - name: Build Docker image
      run: docker build -t my-python-app -f Dockerfile.local .

    - name: Run Docker container
      run: docker run my-python-app
