name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --fix-missing librbd1
        python -m pip install --upgrade pip
        pip install flake8
        # Add other dependencies as needed

    - name: Linting
      run: flake8 pycode.py

    - name: Testing
      run: python pycode.py

  deploy_local:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up deployment environment
        run: |
          sudo apt-get update
          sudo apt-get install -y --fix-missing librbd1
          sudo apt-get install -y python
          python -m pip install --upgrade pip

      - name: Deploy locally
        run: bash deploy_local.sh
